name: Gravity Inn
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5170786031521857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebd6aa'
    - '#462321'
    - '#9f4836'
    - '#d08724'
    - '#95a976'
  brandStrength: 0.6994374187197536
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.9389345138333738
purpose: []
