name: Gravity Inn
favicon: null
layout_spectrum: 0.7013259606901556
typography_spectrum: 0.5170786031521857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c211d'
    - '#767072'
    - '#88a452'
    - '#e7c8b5'
  brandStrength: 0.6994374187197536
  lightness: 0.871930034365505
  saturation: 0.7475932068191469
  rhythmicContrast: 0.9389345138333738
purpose: []
